namespace Envis10n.TelNet.Constants
{
    public struct TelnetOption
    {
        public const byte
            BINARY = 0,
            ECHO = 1,
            RCP = 2,
            SGA = 3,
            NAMS = 4,
            STATUS = 5,
            TM = 6,
            RCTE = 7,
            NAOL = 8,
            NAOP = 9,
            NAOCRD = 10,
            NAOHTS = 11,
            NAOHTD = 12,
            NAOFFD = 13,
            NAOVTS = 14,
            NAOVTD = 15,
            NAOLFD = 16,
            XASCII = 17,
            LOGOUT = 18,
            BM = 19,
            DET = 20,
            SUPDUP = 21,
            SUPDUPOUTPUT = 22,
            SNDLOC = 23,
            TTYPE = 24,
            EOR = 25,
            TUID = 26,
            OUTMRK = 27,
            TTYLOC = 28,
            _3270REGIME = 29,
            X3PAD = 30,
            NAWS = 31,
            TSPEED = 32,
            LFLOW = 33,
            LINEMODE = 34,
            XDISPLOC = 35,
            ENVIRON = 36,
            AUTHENTICATION = 37,
            ENCRYPT = 38,
            NEWENVIRON = 39,
            MSSP = 70,
            ZMP = 93,
            EXOPL = 255,
            MCCP2 = 86,
            MCCP3 = 87,
            GMCP = 201;
    }
}